"""Reverse-proxy config for the hub's Caddy sidecar.

A LAN browser can't reach a site's Netwatch (:8090) / Kuma (:3001) on its
WireGuard IP (10.8.0.x) — but the hub can, because it shares wg-easy's network
namespace (where wg0 lives). The `hub-proxy` Caddy sidecar shares that same netns
and publishes one LAN port per site-service, reverse-proxying it over the tunnel.
So the dashboards open *through the hub* with no VPN client on the user's machine.

Each proxied port is gated by HTTP Basic Auth using the hub password (the site
apps have no login of their own) — see auth.proxy_basic_hash. If no hash is
available yet the proxy is left empty (fail closed), never exposed unprotected.

This module decides which sites to proxy, assigns stable ports from a range,
renders the Caddyfile, and hot-reloads Caddy via its admin API. Caddy and the hub
share localhost (same netns), so the admin API is reachable at localhost:2019 —
the same trick wgeasy.py uses for wg-easy at localhost:51821.
"""
import ipaddress
import os

import requests

import hubconfig

VPN_SUBNET = ipaddress.ip_network("10.8.0.0/24")
CADDY_ADMIN = "http://localhost:2019"
CADDYFILE = os.path.join(os.environ.get("HUB_DATA", "/data"), "caddy", "Caddyfile")


def port_range():
    """(low, high) inclusive. MUST match the published range in
    hub/docker-compose.yml — HUB_PROXY_RANGE keeps code and compose in sync."""
    spec = os.environ.get("HUB_PROXY_RANGE", "8200-8231")
    try:
        lo, hi = (int(x) for x in spec.split("-", 1))
        if lo <= hi:
            return lo, hi
    except (ValueError, TypeError):
        pass
    return 8200, 8231


def is_proxied(site):
    """True only for real VPN sites (10.8.0.x). The home site uses a LAN IP the
    browser already reaches, so it stays linked direct (no proxy)."""
    try:
        return ipaddress.ip_address(site.get("vpn_ip", "")) in VPN_SUBNET
    except ValueError:
        return False


def _valid(port, lo, hi):
    return isinstance(port, int) and lo <= port <= hi


def assign_ports(cfg):
    """Ensure every proxied site has a stable proxy_netwatch_port (+ proxy_kuma_port
    when it has a Kuma URL). Existing valid assignments are kept; new ones get the
    lowest free port in range; ports are freed when a site stops being proxied or
    drops Kuma. Returns (cfg, changed)."""
    lo, hi = port_range()
    sites = cfg["sites"]
    used = {p for s in sites for p in
            (s.get("proxy_netwatch_port"), s.get("proxy_kuma_port")) if _valid(p, lo, hi)}

    def take():
        for p in range(lo, hi + 1):
            if p not in used:
                used.add(p)
                return p
        return None

    changed = False
    for s in sites:
        if not is_proxied(s):
            for k in ("proxy_netwatch_port", "proxy_kuma_port"):
                if k in s:
                    del s[k]
                    changed = True
            continue
        if not _valid(s.get("proxy_netwatch_port"), lo, hi):
            p = take()
            if p is None:
                print(f"[proxycfg] port range {lo}-{hi} exhausted — "
                      f"{s['id']} netwatch not proxied", flush=True)
            else:
                s["proxy_netwatch_port"] = p
                changed = True
        if s.get("kuma_url"):
            if not _valid(s.get("proxy_kuma_port"), lo, hi):
                p = take()
                if p is None:
                    print(f"[proxycfg] port range {lo}-{hi} exhausted — "
                          f"{s['id']} kuma not proxied", flush=True)
                else:
                    s["proxy_kuma_port"] = p
                    changed = True
        elif "proxy_kuma_port" in s:
            del s["proxy_kuma_port"]
            changed = True
    return cfg, changed


def _basic_auth():
    """Caddy basic_auth directive (bcrypt) for the hub password, or '' if no hash
    is stored yet."""
    h = (hubconfig.load().get("auth") or {}).get("proxy_basic_hash") or ""
    if not h:
        return ""
    return "\tbasic_auth {\n\t\tadmin " + h + "\n\t}\n"


def _kuma_hostport(site):
    """host:port parsed from kuma_url (strip scheme + any path)."""
    url = (site.get("kuma_url") or "").strip()
    if not url:
        return None
    hp = url.split("://", 1)[-1].split("/", 1)[0]
    return hp or None


def render_caddyfile(cfg):
    """Return the Caddyfile text. Fail closed: if there's no Basic Auth hash yet,
    emit a config with NO proxied sites rather than exposing them unprotected."""
    head = ["# Generated by the hub — do not edit by hand.", "{", "\tauto_https off", "}", ""]
    basic = _basic_auth()
    if not basic:
        print("[proxycfg] no hub password hash yet — site proxy disabled. "
              "Log in / re-save the hub password to enable LAN access.", flush=True)
        return "\n".join(head) + "\n"

    blocks = []

    def block(port, target, label):
        blocks.append(f"# {label}\n:{port} {{\n{basic}\treverse_proxy {target}\n}}\n")

    for s in cfg["sites"]:
        if not is_proxied(s):
            continue
        nw = s.get("proxy_netwatch_port")
        if _valid(nw, *port_range()):
            block(nw, f"{s['vpn_ip']}:{s.get('netwatch_port', 8090)}", f"{s['id']} netwatch")
        kp, kt = s.get("proxy_kuma_port"), _kuma_hostport(s)
        if _valid(kp, *port_range()) and kt:
            block(kp, kt, f"{s['id']} kuma")
    return "\n".join(head) + "\n" + "\n".join(blocks)


def _reload(text):
    """Hot-reload Caddy via its admin API (zero-downtime). Best-effort: at hub
    startup Caddy may not be up yet, but it reads the file on boot anyway."""
    try:
        r = requests.post(f"{CADDY_ADMIN}/load", data=text.encode(),
                          headers={"Content-Type": "text/caddyfile"}, timeout=5)
        if r.status_code >= 300:
            print(f"[proxycfg] caddy reload HTTP {r.status_code}: {r.text[:200]}", flush=True)
            return False
        return True
    except requests.RequestException as e:
        print(f"[proxycfg] caddy reload skipped ({e}) — file written, "
              "Caddy will load it on next start", flush=True)
        return False


def write_caddyfile(text):
    os.makedirs(os.path.dirname(CADDYFILE), exist_ok=True)
    tmp = CADDYFILE + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, CADDYFILE)
    _reload(text)


def sync(cfg=None):
    """Assign ports (persist if changed), regenerate the Caddyfile, reload Caddy.
    Call at startup and after any change to the site registry or hub password."""
    cfg = cfg or hubconfig.load()
    cfg, changed = assign_ports(cfg)
    if changed:
        hubconfig.save(cfg)
        cfg = hubconfig.load()
    write_caddyfile(render_caddyfile(cfg))
    return cfg


def links(site, host):
    """(netwatch_url, kuma_url) for the dashboard buttons, given the LAN host the
    browser used. Proxied sites -> hub host + assigned port; others -> direct."""
    if is_proxied(site):
        nw = site.get("proxy_netwatch_port")
        kp = site.get("proxy_kuma_port")
        return (f"http://{host}:{nw}" if nw else "",
                f"http://{host}:{kp}" if (kp and site.get("kuma_url")) else "")
    port = site.get("netwatch_port", 8090)
    return f"http://{site['vpn_ip']}:{port}", site.get("kuma_url") or ""
